name = "JointEnergyModels"
uuid = "48c56d24-211d-4463-bbc0-7a701b291131"
version = "0.1.9"
authors = ["Patrick Altmeyer"]

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ComputationalResources = "ed09eef8-17a6-5b46-8889-db040fac31e3"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
EnergySamplers = "f446124b-5d5e-4171-a6dd-a1d99768d3ce"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
MLJFlux = "094fc8d1-fd35-5302-93ea-dabda2abf845"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
TaijaBase = "10284c91-9f28-4c9a-abbf-ee43576dfff6"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Aqua = "0.8"
CategoricalArrays = "0.10"
ChainRulesCore = "1.16"
ComputationalResources = "0.3"
Distributions = "0.25"
EnergySamplers = "1.0.0"
Flux = "0.13, 0.14, 0.15, 0.16"
MLJFlux = "0.2, 0.3, 0.4, 0.5, 0.6"
MLJModelInterface = "1.8"
MLUtils = "0.4"
Optimisers = "0.3, 0.4"
ProgressMeter = "1.7"
Random = "1"
Reexport = "1.2.2"
StatsBase = "0.33, 0.34"
Tables = "1"
TaijaBase = "1.1.0"
Test = "1"
Zygote = "0.6, 0.7"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
